import type { ReactNode } from "react";
import {
  SiNextdotjs,
  SiReact,
  SiNestjs,
  SiPostgresql,
  SiAngular,
  SiDocker,
  SiLinux,
  SiGit,
  SiTypescript,
  SiIonic,
  SiMongodb,
  SiExpress,
  SiPostman,
  SiSwagger,
  SiOwasp,
  SiPython,
  SiRender,
  SiKubernetes,
  SiApachespark,
  SiApachekafka,
  SiJavascript,
  SiNodedotjs,
  SiMysql,
  SiRedis,
  SiGraphql,
  SiFirebase,
  SiVercel,
  SiGithubactions,
  SiJest,
  SiFigma,
} from "react-icons/si";
import { MdSecurity, MdOutlineVpnLock, MdOutlinePolicy } from "react-icons/md";
import {
  FaBug,
  FaCode,
  FaServer,
  FaCloud,
  FaDatabase,
  FaShieldAlt,
  FaLock,
  FaNetworkWired,
  FaUserSecret,
  FaKey,
  FaTerminal,
  FaTools,
  FaStar,
  FaHeart,
  FaBriefcase,
  FaAward,
  FaCheckCircle,
  FaUsers,
  FaCalendarAlt,
  FaPhoneAlt,
  FaEnvelope,
  FaMapMarkerAlt,
  FaLightbulb,
  FaHeartbeat,
  FaBook,
  FaHandshake,
  FaGraduationCap,
  FaPaintBrush,
  FaUtensils,
  FaCar,
  FaHome,
  FaGavel,
  FaStethoscope,
} from "react-icons/fa";

// Registro central de íconos: la clave (icon key) es lo único que se guarda
// en la base de datos. Así, tanto el Home público como el panel de admin
// (para el selector de íconos) usan exactamente el mismo mapa.
export const ICON_REGISTRY: Record<string, ReactNode> = {
  nextjs: <SiNextdotjs />,
  react: <SiReact />,
  angular: <SiAngular />,
  ionic: <SiIonic />,
  nestjs: <SiNestjs />,
  express: <SiExpress />,
  nodejs: <SiNodedotjs />,
  typescript: <SiTypescript />,
  javascript: <SiJavascript />,
  python: <SiPython />,
  postgresql: <SiPostgresql />,
  mongodb: <SiMongodb />,
  mysql: <SiMysql />,
  redis: <SiRedis />,
  graphql: <SiGraphql />,
  docker: <SiDocker />,
  kubernetes: <SiKubernetes />,
  linux: <SiLinux />,
  git: <SiGit />,
  githubactions: <SiGithubactions />,
  firebase: <SiFirebase />,
  vercel: <SiVercel />,
  render: <SiRender />,
  apachespark: <SiApachespark />,
  apachekafka: <SiApachekafka />,
  jest: <SiJest />,
  figma: <SiFigma />,
  owasp: <SiOwasp />,
  postman: <SiPostman />,
  swagger: <SiSwagger />,
  bug: <FaBug />,
  security: <MdSecurity />,
  shield: <FaShieldAlt />,
  lock: <FaLock />,
  key: <FaKey />,
  vpn: <MdOutlineVpnLock />,
  policy: <MdOutlinePolicy />,
  network: <FaNetworkWired />,
  incognito: <FaUserSecret />,
  terminal: <FaTerminal />,
  tools: <FaTools />,
  code: <FaCode />,
  server: <FaServer />,
  cloud: <FaCloud />,
  database: <FaDatabase />,
  star: <FaStar />,
  heart: <FaHeart />,
  briefcase: <FaBriefcase />,
  award: <FaAward />,
  check: <FaCheckCircle />,
  users: <FaUsers />,
  calendar: <FaCalendarAlt />,
  phone: <FaPhoneAlt />,
  mail: <FaEnvelope />,
  location: <FaMapMarkerAlt />,
  idea: <FaLightbulb />,
  health: <FaHeartbeat />,
  book: <FaBook />,
  handshake: <FaHandshake />,
  education: <FaGraduationCap />,
  design: <FaPaintBrush />,
  food: <FaUtensils />,
  automotive: <FaCar />,
  home: <FaHome />,
  legal: <FaGavel />,
  medical: <FaStethoscope />,
};

export type IconKey = keyof typeof ICON_REGISTRY;

export const ICON_OPTIONS: { key: string; label: string }[] = [
  { key: "star", label: "⭐ Destacado" },
  { key: "heart", label: "❤️ Favorito" },
  { key: "briefcase", label: "💼 Profesional" },
  { key: "award", label: "🏆 Logro / Certificación" },
  { key: "check", label: "✅ Completado" },
  { key: "users", label: "👥 Equipo / Clientes" },
  { key: "handshake", label: "🤝 Acuerdo / Confianza" },
  { key: "calendar", label: "📅 Agenda / Horario" },
  { key: "phone", label: "📞 Teléfono" },
  { key: "mail", label: "✉️ Correo" },
  { key: "location", label: "📍 Ubicación" },
  { key: "idea", label: "💡 Idea" },
  { key: "health", label: "💗 Salud" },
  { key: "medical", label: "🩺 Médico" },
  { key: "book", label: "📖 Educación / Estudio" },
  { key: "education", label: "🎓 Título académico" },
  { key: "design", label: "🎨 Diseño" },
  { key: "food", label: "🍽️ Gastronomía" },
  { key: "automotive", label: "🚗 Automotriz" },
  { key: "home", label: "🏠 Hogar / Inmobiliaria" },
  { key: "legal", label: "⚖️ Legal" },
  { key: "code", label: "💻 Código (genérico)" },
  { key: "server", label: "🖥️ Servidor" },
  { key: "cloud", label: "☁️ Cloud" },
  { key: "database", label: "🗄️ Base de datos" },
  { key: "nextjs", label: "Next.js" },
  { key: "react", label: "React" },
  { key: "angular", label: "Angular" },
  { key: "ionic", label: "Ionic" },
  { key: "nestjs", label: "NestJS" },
  { key: "express", label: "Express" },
  { key: "nodejs", label: "Node.js" },
  { key: "typescript", label: "TypeScript" },
  { key: "javascript", label: "JavaScript" },
  { key: "python", label: "Python" },
  { key: "postgresql", label: "PostgreSQL" },
  { key: "mongodb", label: "MongoDB" },
  { key: "mysql", label: "MySQL" },
  { key: "redis", label: "Redis" },
  { key: "graphql", label: "GraphQL" },
  { key: "docker", label: "Docker" },
  { key: "kubernetes", label: "Kubernetes" },
  { key: "linux", label: "Linux" },
  { key: "git", label: "Git" },
  { key: "githubactions", label: "GitHub Actions" },
  { key: "firebase", label: "Firebase" },
  { key: "vercel", label: "Vercel" },
  { key: "render", label: "Render" },
  { key: "apachespark", label: "Apache Spark" },
  { key: "apachekafka", label: "Apache Kafka" },
  { key: "jest", label: "Jest" },
  { key: "figma", label: "Figma" },
  { key: "owasp", label: "OWASP" },
  { key: "postman", label: "Postman" },
  { key: "swagger", label: "Swagger / OpenAPI" },
  { key: "bug", label: "Bug / Vulnerabilidad" },
  { key: "security", label: "Seguridad" },
  { key: "shield", label: "Escudo" },
  { key: "lock", label: "Candado" },
  { key: "key", label: "Llave / Auth" },
  { key: "vpn", label: "VPN" },
  { key: "policy", label: "Política / Compliance" },
  { key: "network", label: "Red" },
  { key: "incognito", label: "Anonimato" },
  { key: "terminal", label: "Terminal" },
  { key: "tools", label: "Herramientas" },
];

export function getIcon(key: string): ReactNode {
  return ICON_REGISTRY[key] ?? ICON_REGISTRY.code;
}
